-- Add missing columns to orders table
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items         JSONB DEFAULT '[]';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal      DECIMAL(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_cost DECIMAL(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount      DECIMAL(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount  DECIMAL(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_link  TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_addr JSONB DEFAULT '{}';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_number  VARCHAR(50) DEFAULT '';

SELECT 'Orders table updated' AS status;
